#!/usr/bin/env node

const execa = require('execa')

const typeScriptBuild = () =>
    execa(
        'tsc',
        [],
        {
            stdio: 'inherit',
        }
    );

const createToc = () =>
    execa(
        'yarn run createtoc',
        [],
        {
            stdio: 'inherit',
        }
    );

typeScriptBuild();
createToc();

