#!/usr/bin/env node

const packageJson = require('../../package.json');

const execa = require('execa')

const typeScriptBuild = () =>
    execa(
        'tsc',
        [],
        {
            stdio: 'inherit',
        }
    );

const createToc = () =>
    execa(
        `yarn run createtoc && git add ${packageJson.tocList} && git commit -m "Add TOC update"`,
        [],
        {
            stdio: 'inherit',
        }
    );


typeScriptBuild();
createToc();

